<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class WebappTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->nonAdminUser = factory(User::class)->create();
    }

    /** @test */
    public function non_logged_user_see_home_page()
    {
        $response = $this->get('/');
        $response->assertStatus(200);
    }

    /** @test */
    public function logged_in_user_is_redirected_to_projects()
    {
        $response = $this->actingAs($this->nonAdminUser)->get('/');
        $response->assertRedirect('/projects');
    }

    /** @test */
    public function admin_see_link_to_admin_area()
    {
        $adminUser = $this->createUserWithPermissionTo('do:admin:actions');
        $response = $this->actingAs($adminUser)->get('/');
        $response->assertSee('class="nav-link" href="/admin/roles"');
    }

    /** @test */
    public function non_admin_cannot_see_link_to_admin_area()
    {
        $response = $this->actingAs($this->nonAdminUser)->get('/');
        $response->assertDontSee('class="nav-link" href="/admin/roles"');
    }
}
