<?php

namespace Tests\Feature\Controller;

use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RolesTest extends TestCase
{
    use DatabaseMigrations;

    public  function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->nonAdminUser = factory(User::class)->create();
    }

    /** @test */
    public function non_admin_cannot_see_all_roles()
    {
        $response = $this->actingAs($this->nonAdminUser)->get('/admin/roles');
        $response->assertStatus(403);
    }

    /** @test */
    public function admin_can_see_all_roles()
    {
        $adminUser = $this->createUserWithPermissionTo('do:admin:actions');

        $respone = $this->actingAs($adminUser)->get('/admin/roles');
        $respone->assertStatus(200);
        $respone->assertSee('Roles');
    }
}
