#!/usr/bin/env php
<?php

echo "----> " . getcwd() . "\n";
$ref = $_SERVER['argv'][1];
echo "----> $ref \n";

print_r($_SERVER);

if ($ref == "refs/heads/master") {
    echo "----> not allowed $ref is protected branch but allowing to push \n";
    //exit(1);
}
